DROP INDEX IF EXISTS IDX_TITLE;


DROP TABLE IF EXISTS SONGS;


CREATE TABLE IF NOT EXISTS SONGS (
	ID CHARACTER VARYING(50) NOT NULL,
	TITLE CHARACTER VARYING(3000) NOT NULL,
	DANCEABILITY numeric NOT NULL,
	ENERGY numeric NOT NULL,
	KEY numeric NOT NULL,
	LOUDNESS numeric NOT NULL,
	MODE numeric NOT NULL,
	ACOUSTICNESS numeric NOT NULL,
	INSTRUMENTALNESS numeric NOT NULL,
	LIVENESS numeric NOT NULL,
	VALENCE numeric NOT NULL,
	TEMPO numeric NOT NULL,
	DURATION_MS numeric NOT NULL,
	TIME_SIGNATURE numeric NOT NULL,
	NUM_BARS numeric NOT NULL,
	NUM_SECTIONS numeric NOT NULL,
	NUM_SEGMENTS numeric NOT NULL,
	CLASS numeric NOT NULL,
	RATING integer DEFAULT 0, 
	CONSTRAINT SONGS_PKEY PRIMARY KEY (ID),
	CONSTRAINT SONGS_TITLE_KEY UNIQUE (TITLE)
);


CREATE INDEX IF NOT EXISTS IDX_TITLE ON SONGS (TITLE);